# Generated by Django 4.1.2 on 2022-11-04 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_address_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1784ab3e-f3bb-4693-a921-31b9dc9f8b6c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
