# Generated by Django 4.1.3 on 2022-11-04 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_uid_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a8fd7b60-bc92-4ff8-8b5d-2f2d1cb4047c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
