# Generated by Django 4.1.2 on 2022-11-04 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ad2a94ae-95d1-403c-b8ca-9a4d8b003fbd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ad2a94ae-95d1-403c-b8ca-9a4d8b003fbd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ad2a94ae-95d1-403c-b8ca-9a4d8b003fbd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
