# Generated by Django 4.1.2 on 2022-11-04 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_category_uid_alter_product_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('27ec1851-82e5-4eb0-b5d2-f19b67242bc3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('27ec1851-82e5-4eb0-b5d2-f19b67242bc3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('27ec1851-82e5-4eb0-b5d2-f19b67242bc3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
