# Generated by Django 4.1.3 on 2022-11-04 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_category_uid_alter_product_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(upload_to="images/categories"),
        ),
        migrations.AlterField(
            model_name="category",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("7e210a2e-7503-4b1e-97f8-cb02fb27ca0e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("7e210a2e-7503-4b1e-97f8-cb02fb27ca0e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="images/products"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("7e210a2e-7503-4b1e-97f8-cb02fb27ca0e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
