# Generated by Django 4.1.3 on 2022-11-04 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_category_category_image_alter_category_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a8fd7b60-bc92-4ff8-8b5d-2f2d1cb4047c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a8fd7b60-bc92-4ff8-8b5d-2f2d1cb4047c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a8fd7b60-bc92-4ff8-8b5d-2f2d1cb4047c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
