# Generated by Django 4.1.3 on 2022-11-05 09:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_category_uid_alter_product_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/products",
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category_images",
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(name="ProductImage",),
    ]
