# Generated by Django 4.1.3 on 2022-11-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0010_product_product_image_alter_category_category_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products_images",
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
    ]
