# Generated by Django 4.1.3 on 2022-11-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_remove_product_description_tickets"),
    ]

    operations = [
        migrations.RemoveField(model_name="tickets", name="category",),
        migrations.AddField(
            model_name="tickets",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="projects.product",
            ),
        ),
    ]
